import pandas as pd
import plotly.graph_objects as go
import streamlit as st
import yfinance as yf


st.set_page_config(page_title="FinX Scripts", page_icon="📈", layout="wide")


# Raw NSE symbols collected from the provided stock universe.
STOCKS = [
    "RELIANCE",
    "HDFCBANK",
    "BHARTIARTL",
    "ICICIBANK",
    "SBIN",
    "TCS",
    "TVSMOTOR",
    "BAJFINANCE",
    "LT",
    "HINDUNILVR",
    "LICI",
    "INFY",
    "SUNPHARMA",
    "ADANIPOWER",
    "MARUTI",
    "ADANIPORTS",
    "AXISBANK",
    "M&M",
    "ITC",
    "KOTAKBANK",
    "NTPC",
    "ONGC",
    "TITAN",
    "ADANIENT",
    "ULTRACEMCO",
    "M&MFIN",
    "HCLTECH",
    "JSWSTEEL",
    "BEL",
    "BAJAJ-AUTO",
    "HAL",
    "BAJAJFINSV",
    "COALINDIA",
    "POWERGRID",
    "NESTLEIND",
    "DMART",
    "HINDZINC",
    "TATASTEEL",
    "ASIANPAINT",
    "HINDALCO",
    "ETERNAL",
    "ADANIGREEN",
    "SHRIRAMFIN",
    "WIPRO",
    "GRASIM",
    "IOC",
    "EICHERMOT",
    "SBILIFE",
    "DIVISLAB",
    "VBL",
    "BSE",
    "INDIGO",
    "SOLARINDS",
    "ADANIENSOL",
    "POWERINDIA",
    "ICICIAMC",
    "JIOFIN",
    "TORNTPHARM",
    "CUMMINSIND",
    "PIDILITIND",
    "IDEA",
    "TRENT",
    "HYUNDAI",
    "DLF",
    "BHEL",
    "PFC",
    "TECHM",
    "ABB",
    "TMCV",
    "MOTHERSON",
    "POLYCAB",
    "BANKBARODA",
    "CGPOWER",
    "TMPV",
    "MUTHOOTFIN",
    "TATAPOWER",
    "SIEMENS",
    "HDFCLIFE",
    "VEDL",
    "CHOLAFIN",
    "BRITANNIA",
    "TATACAP",
    "BPCL",
    "IRFC",
    "JINDALSTEL",
    "ENRIN",
    "LTM",
    "UNIONBANK",
    "GVT&D",
    "TATACONSUM",
    "GROWW",
    "PNB",
    "BAJAJHLDNG",
    "APOLLOHOSP",
    "CANBK",
    "HDFCAMC",
    "CIPLA",
    "INDUSTOWER",
    "DRREDDY",
    "INDIANB",
    "MARICO",
    "BOSCHLTD",
    "AMBUJACEM",
    "MANKIND",
    "ZYDUSLIFE",
    "MAXHEALTH",
    "GODREJCP",
    "LUPIN",
    "LGEINDIA",
    "GAIL",
    "GMRAIRPORT",
    "HEROMOTOCO",
    "MAZDOCK",
    "JSWENERGY",
    "INDHOTEL",
    "UNITDSPR",
    "ABCAPITAL",
    "BHARATFORG",
    "ASHOKLEY",
    "LLOYDSME",
    "NTPCGREEN",
    "ICICIGI",
    "MEESHO",
    "SHREECEM",
    "LODHA",
    "MCX",
    "RECLTD",
    "AUROPHARMA",
    "WAAREEENER",
    "POLICYBZR",
    "LENSKART",
    "OFSS",
    "SAIL",
    "OIL",
    "HINDPETRO",
    "PERSISTENT",
    "DABUR",
    "NHPC",
    "BHARTIHEXA",
    "IDBI",
    "NYKAA",
    "NMDC",
    "SRF",
    "TORNTPOWER",
    "HAVELLS",
    "NATIONALUM",
    "ICICIPRULI",
    "PAYTM",
    "FORTIS",
    "LAURUSLABS",
    "AUBANK",
    "SUZLON",
    "FEDERALBNK",
    "SWIGGY",
    "NAM-INDIA",
    "BIOCON",
    "INDUSINDBK",
    "LTF",
    "YESBANK",
    "BAJAJHFL",
    "GICRE",
    "ATGL",
    "GLENMARK",
    "DIXON",
    "ALKEM",
    "IOB",
    "BANKINDIA",
    "SCHAEFFLER",
    "PHOENIXLTD",
    "LINDEINDIA",
    "NAUKRI",
    "UNOMINDA",
    "JSL",
    "MAHABANK",
    "PRESTIGE",
    "COLPAL",
    "SBICARD",
    "BERGEPAINT",
    "OBEROIRLTY",
    "IDFCFIRSTB",
    "ABBOTINDIA",
    "TIINDIA",
    "VMM",
    "RVNL",
    "FACT",
    "MFSL",
    "HDBFS",
    "COROMANDEL",
    "JSWINFRA",
    "MRF",
    "HINDCOPPER",
    "UPL",
    "THERMAX",
    "GODREJPROP",
    "APLAPOLLO",
    "MOTILALOFS",
    "APARINDS",
    "PATANJALI",
    "TATACOMM",
    "SUNDARMFIN",
    "NLCINDIA",
    "KEI",
    "BDL",
    "RADICO",
    "COFORGE",
    "360ONE",
    "PREMIERENE",
    "SUPREMEIND",
    "PIIND",
    "ANTHEM",
    "PIRAMALFIN",
    "AIIL",
    "VOLTAS",
    "PAGEIND",
    "MPHASIS",
    "IRCTC",
    "IPCALAB",
    "BALKRISIND",
    "JKCEMENT",
    "HUDCO",
    "FLUOROCHEM",
    "AJANTPHARM",
    "GLAXO",
    "PETRONET",
    "COCHINSHIP",
    "ASTERDM",
    "NH",
    "ASTRAL",
    "CONCOR",
    "LTTS",
    "GODREJIND",
    "AIAENG",
    "GLAND",
    "SONACOMS",
    "NAVINFLUOR",
    "GODFRYPHLP",
    "ENDURANCE",
    "UBL",
    "IREDA",
    "KALYANKJIL",
    "POONAWALLA",
    "3MINDIA",
    "ATHERENERG",
    "JBCHEPHARM",
    "WELCORP",
    "BLUESTARCO",
    "DELHIVERY",
    "TATAINVEST",
    "MEDANTA",
    "EMCURE",
    "KPRMILL",
    "ESCORTS",
    "PWL",
    "DALBHARAT",
    "ITCHOTELS",
    "HEXT",
    "JUBLFOOD",
    "SCHNEIDER",
    "BANDHANBNK",
    "CRISIL",
    "UCOBANK",
    "CENTRALBK",
    "CHOLAHLDNG",
    "STARHEALTH",
    "GRSE",
    "KIMS",
    "LICHSGFIN",
    "MANAPPURAM",
    "ANGELONE",
    "ABSLAMC",
    "ANANDRATHI",
    "HSCL",
    "SJVN",
    "EXIDEIND",
    "GODIGIT",
    "CPPLUS",
    "LALPATHLAB",
    "IKS",
    "KARURVYSYA",
    "PNBHOUSING",
    "TIMKEN",
    "ITI",
    "TATATECH",
    "ZFCVINDIA",
    "NUVAMA",
    "NIACL",
    "HONAUT",
    "MSUMI",
    "WOCKPHARMA",
    "TATAELXSI",
    "MRPL",
    "SHYAMMETL",
    "CDSL",
    "AWL",
    "IRB",
    "ACC",
    "NBCC",
    "GILLETTE",
    "AEGISLOG",
    "DEEPAKNTR",
    "FORCEMOT",
    "AMBER",
    "SAILIFE",
    "KIRLOSENG",
    "TENNIND",
    "CESC",
    "APOLLOTYRE",
    "GESHIP",
    "PTCIL",
    "ACUTAAS",
    "PPLPHARMA",
    "SUMICHEM",
    "RRKABEL",
    "AEGISVOPAK",
    "NETWEB",
    "IGL",
    "BAYERCROP",
    "DATAPATTNS",
    "PFIZER",
    "ONESOURCE",
    "NEULANDLAB",
    "HFCL",
    "HBLENGINE",
    "KPIL",
    "ASAHIINDIA",
    "AADHARHFC",
    "TRITURBINE",
    "RAMCOCEM",
    "CREDITACC",
    "NATCOPHARM",
    "ATUL",
    "KPITTECH",
    "GPIL",
    "CRAFTSMAN",
    "GMDCLTD",
    "SUNTV",
    "AFFLE",
    "RBLBANK",
    "ERIS",
    "CARBORUNIV",
    "EIHOTEL",
    "KAYNES",
    "IIFL",
    "SAGILITY",
    "SARDAEN",
    "SYRMA",
    "CAMS",
    "GRANULES",
    "SYNGENE",
    "EMAMILTD",
    "CROMPTON",
    "BELRISE",
    "TATACHEM",
    "CUB",
    "URBANCO",
    "EMMVEE",
    "CASTROLIND",
    "ELGIEQUIP",
    "CGCL",
    "CHAMBLFERT",
    "NAVA",
    "VTL",
    "ANANTRAJ",
    "CIEINDIA",
    "REDINGTON",
    "CHALET",
    "FSL",
    "PINELABS",
    "DCMSHRIRAM",
    "ACMESOLAR",
    "BIKAJI",
    "AARTIIND",
    "KAJARIACER",
    "DEEPAKFERT",
    "BRIGADE",
    "IFCI",
    "JSWCEMENT",
    "INOXWIND",
    "SAMMAANCAP",
    "ZYDUSWELL",
    "OLAELEC",
    "GALLANTT",
    "JUBLPHARMA",
    "COHANCE",
    "FINCABLES",
    "GABRIEL",
    "ANURAS",
    "CAPLIPOINT",
    "SCI",
    "JYOTICNC",
    "BEML",
    "IGIL",
    "JBMA",
    "CHENNPETRO",
    "NIVABUPA",
    "ARE&M",
    "ABDL",
    "CHOICEIN",
    "POLYMED",
    "J&KBANK",
    "SOBHA",
    "CCL",
    "CEMPRO",
    "ZENTEC",
    "GRAPHITE",
    "DEVYANI",
    "KFINTECH",
    "ABREL",
    "ECLERX",
    "EIDPARRY",
    "USHAMART",
    "JINDALSAW",
    "LTFOODS",
    "TECHNOE",
    "TRAVELFOOD",
    "DOMS",
    "RAINBOW",
    "THELEELA",
    "WELSPUNLIV",
    "ENGINERSIN",
    "JAINREC",
    "APTUS",
    "JSWDULUX",
    "IRCON",
    "PGEL",
    "CANHLIFE",
    "FIVESTAR",
    "VIJAYA",
    "SPLPETRO",
    "PARADEEP",
    "CEATLTD",
    "TBOTEK",
    "NSLNISP",
    "KEC",
    "JPPOWER",
    "INDIACEM",
    "ABLBL",
    "INDGN",
    "MINDACORP",
    "TRIDENT",
    "JMFINANCIL",
    "UTIAMC",
    "INDIAMART",
    "GRAVITA",
    "TEGA",
    "JUBLINGREA",
    "CONCORDBIO",
    "JWL",
    "HONASA",
    "SIGNATURE",
    "FIRSTCRY",
    "PCBL",
    "BLUEDART",
    "HEG",
    "HOMEFIRST",
    "NUVOCO",
    "AFCONS",
    "RPOWER",
    "IEX",
    "CANFINHOME",
    "ZENSARTECH",
    "BLS",
    "ELECON",
    "WHIRLPOOL",
    "AAVAS",
    "BALRAMCHIN",
    "ACE",
    "MGL",
    "BBTC",
    "JKTYRE",
    "RAILTEL",
    "RKFORGE",
    "TITAGARH",
    "CYIENT",
    "SWANCORP",
    "SBFC",
    "OLECTRA",
    "RITES",
    "PVRINOX",
    "INTELLECT",
    "MMTC",
    "NCC",
    "TARIL",
    "BSOFT",
    "BATAINDIA",
    "LEMONTREE",
    "CARTRADE",
    "TEJASNET",
    "TTML",
    "CLEAN",
    "RHIM",
    "ZEEL",
    "SAREGAMA",
    "ABFRL",
    "BLUEJET",
    "SONATSOFTW",
    "LATENTVIEW",
    "NEWGEN",
    "SAPPHIRE",
    "MAPMYINDIA",
]

# Normalize symbols for Yahoo Finance, avoid duplicates, then sort them.
STOCKS = list(
    {
        symbol if symbol.endswith(".NS") else f"{symbol}.NS"
        for symbol in STOCKS
    }
)
STOCKS = sorted(STOCKS)


# Map user-friendly labels to yfinance period values.
PERIOD_OPTIONS = {
    "1 month": "1mo",
    "3 months": "3mo",
    "6 months": "6mo",
    "1 year": "1y",
    "2 years": "2y",
    "5 years": "5y",
    "Maximum available data": "max",
}


@st.cache_data(show_spinner=False)
def fetch_stock_data(ticker_symbol: str, period: str) -> pd.DataFrame:
    """Fetch historical stock data for the selected Yahoo Finance ticker."""
    ticker = yf.Ticker(ticker_symbol)
    history = ticker.history(period=period, auto_adjust=False)

    if history.empty:
        raise ValueError(
            f"No data was returned for {ticker_symbol}. "
            "Please select another stock or time period."
        )

    history = history.reset_index()
    history["Date"] = pd.to_datetime(history["Date"]).dt.tz_localize(None)
    return history


def build_price_chart(dataframe: pd.DataFrame, ticker_symbol: str) -> go.Figure:
    """Create an interactive Plotly line chart for closing prices."""
    figure = go.Figure()
    figure.add_trace(
        go.Scatter(
            x=dataframe["Date"],
            y=dataframe["Close"],
            mode="lines",
            name="Close Price",
            line={"width": 3, "color": "#0F766E"},
            hovertemplate="Date: %{x|%d %b %Y}<br>Close: %{y:.2f}<extra></extra>",
        )
    )

    figure.update_layout(
        title=f"{ticker_symbol} Closing Price",
        xaxis_title="Date",
        yaxis_title="Price",
        template="plotly_white",
        hovermode="x unified",
        margin={"l": 20, "r": 20, "t": 60, "b": 20},
    )
    return figure


# Main app header and description.
st.title("FinX Scripts")
st.write(
    "Track historical stock closing prices with Yahoo Finance data. "
    "Choose an NSE stock and time range to explore the chart instantly."
)
st.caption("All symbols in this app are NSE Yahoo Finance tickers using the `.NS` suffix.")


# Dropdown controls let users pick a stock and time period without typing.
selection_column, period_column = st.columns(2)
selected_ticker = selection_column.selectbox("Select Stock", STOCKS)
selected_label = period_column.selectbox(
    "Select a time period",
    options=list(PERIOD_OPTIONS.keys()),
    index=3,
)
selected_period = PERIOD_OPTIONS[selected_label]


try:
    stock_data = fetch_stock_data(selected_ticker, selected_period)

    latest_close = stock_data["Close"].iloc[-1]
    start_date = stock_data["Date"].min().date()
    end_date = stock_data["Date"].max().date()

    metric_column, range_column = st.columns(2)
    metric_column.metric("Latest Close Price", f"{latest_close:,.2f}")
    range_column.metric("Date Range", f"{start_date} to {end_date}")

    st.plotly_chart(
        build_price_chart(stock_data, selected_ticker),
        use_container_width=True,
    )

    st.subheader("Data Preview")
    preview_columns = ["Date", "Open", "High", "Low", "Close", "Volume"]
    st.dataframe(stock_data[preview_columns].tail(10), use_container_width=True)

except ValueError as error:
    st.warning(str(error))
except Exception:
    st.error(
        f"Something went wrong while fetching data for {selected_ticker}. "
        "Please try another stock or try again in a moment."
    )
